### ISSUE TITLE
Django 1.8 OperationalError: invalid connection option "autocommit"

### ISSUE THREAD

**Issue by paolodina** [edoburu/django-project-template#5]
Running the development server in Django 1.8 with PostgreSQL:

```
Unhandled exception in thread started by <function wrapper at 0x7f49257d5938>
Traceback (most recent call last):
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 223, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    self.check_migrations()
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 164, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 180, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/vagrant/webapp/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: invalid connection option "autocommit"
```

Since Django 1.6, autocommit is turned on by default. This configuration is ignored and can be safely removed ([link](https://docs.djangoproject.com/en/1.7/ref/databases/#autocommit-mode)).

Removing the offending line from settings resolve the issue for me. Now, since the requirements.txt contains `**Django >= 1.8.1**, < 1.9`, the settings file should be updated as well.

**Comment by vdboor** [comment]
Thanks for letting me know, this is now fixed in the master branch!
